// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: telemetry/v1/telemetry.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Integer wire representation saves bandwidth vs string type names.
type Metric_Type int32

const (
	Metric_UNKNOWN            Metric_Type = 0
	Metric_CPU_USAGE_PERCENT  Metric_Type = 1
	Metric_MEMORY_USAGE_BYTES Metric_Type = 2
	Metric_MEMORY_TOTAL_BYTES Metric_Type = 3
	Metric_CPU_TEMP_CELSIUS   Metric_Type = 4
	Metric_NETWORK_TX_BYTES   Metric_Type = 5
	Metric_NETWORK_RX_BYTES   Metric_Type = 6
	Metric_DISK_READ_BYTES    Metric_Type = 7
	Metric_DISK_WRITE_BYTES   Metric_Type = 8
	Metric_DISK_USAGE_BYTES   Metric_Type = 9
	Metric_DISK_TOTAL_BYTES   Metric_Type = 10
)

// Enum value maps for Metric_Type.
var (
	Metric_Type_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "CPU_USAGE_PERCENT",
		2:  "MEMORY_USAGE_BYTES",
		3:  "MEMORY_TOTAL_BYTES",
		4:  "CPU_TEMP_CELSIUS",
		5:  "NETWORK_TX_BYTES",
		6:  "NETWORK_RX_BYTES",
		7:  "DISK_READ_BYTES",
		8:  "DISK_WRITE_BYTES",
		9:  "DISK_USAGE_BYTES",
		10: "DISK_TOTAL_BYTES",
	}
	Metric_Type_value = map[string]int32{
		"UNKNOWN":            0,
		"CPU_USAGE_PERCENT":  1,
		"MEMORY_USAGE_BYTES": 2,
		"MEMORY_TOTAL_BYTES": 3,
		"CPU_TEMP_CELSIUS":   4,
		"NETWORK_TX_BYTES":   5,
		"NETWORK_RX_BYTES":   6,
		"DISK_READ_BYTES":    7,
		"DISK_WRITE_BYTES":   8,
		"DISK_USAGE_BYTES":   9,
		"DISK_TOTAL_BYTES":   10,
	}
)

func (x Metric_Type) Enum() *Metric_Type {
	p := new(Metric_Type)
	*p = x
	return p
}

func (x Metric_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (Metric_Type) Type() protoreflect.EnumType {
	return &file_telemetry_v1_telemetry_proto_enumTypes[0]
}

func (x Metric_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_Type.Descriptor instead.
func (Metric_Type) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1, 0}
}

type TelemetryBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier burned into the device at provisioning time.
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Monotonically increasing per-device counter. Used by the broker for
	// deduplication and by the edge agent to correlate ACKs.
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Batch creation time in microseconds since the Unix epoch.
	// Microsecond precision is required by the SSTable time-partitioning in the
	// storage layer — second-level granularity is insufficient.
	TimestampUs int64 `protobuf:"varint,3,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	// One or more metric readings sampled during this collection interval.
	Metrics []*Metric `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// Ed25519 signature over the canonical protobuf serialization of fields 1–4.
	// Produced by the edge agent's device private key.
	// The ingestion pod validates this against the device's registered public key
	// before enqueuing the batch. Failure routes to the DLQ.
	Signature     []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryBatch) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryBatch) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TelemetryBatch) GetTimestampUs() int64 {
	if x != nil {
		return x.TimestampUs
	}
	return 0
}

func (x *TelemetryBatch) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TelemetryBatch) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  Metric_Type            `protobuf:"varint,1,opt,name=type,proto3,enum=projectz.telemetry.v1.Metric_Type" json:"type,omitempty"`
	// double covers all sensor ranges (temperatures, byte counts, percentages)
	// without precision loss.
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	// Dimension labels for sub-device granularity.
	// Examples: {"cpu": "0"} {"interface": "eth0"} {"disk": "sda"}
	// Allows the storage layer to distinguish per-core, per-interface, per-disk
	// readings of the same MetricType without schema changes.
	Labels        map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetType() Metric_Type {
	if x != nil {
		return x.Type
	}
	return Metric_UNKNOWN
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type IngestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoes the batch's device_id — guards against misdirected responses on a
	// multiplexed connection.
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Echoes the batch's sequence so the agent can release that batch from its
	// retry buffer.
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// False if Ed25519 validation failed, the payload is malformed, or the
	// broker queue is full (backpressure).
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// Human-readable failure reason. Empty when success is true.
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IngestResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *IngestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1ctelemetry/v1/telemetry.proto\x12\x15projectz.telemetry.v1\"\xc3\x01\n" +
	"\x0eTelemetryBatch\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12!\n" +
	"\ftimestamp_us\x18\x03 \x01(\x03R\vtimestampUs\x127\n" +
	"\ametrics\x18\x04 \x03(\v2\x1d.projectz.telemetry.v1.MetricR\ametrics\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xca\x03\n" +
	"\x06Metric\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".projectz.telemetry.v1.Metric.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12A\n" +
	"\x06labels\x18\x03 \x03(\v2).projectz.telemetry.v1.Metric.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x01\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x15\n" +
	"\x11CPU_USAGE_PERCENT\x10\x01\x12\x16\n" +
	"\x12MEMORY_USAGE_BYTES\x10\x02\x12\x16\n" +
	"\x12MEMORY_TOTAL_BYTES\x10\x03\x12\x14\n" +
	"\x10CPU_TEMP_CELSIUS\x10\x04\x12\x14\n" +
	"\x10NETWORK_TX_BYTES\x10\x05\x12\x14\n" +
	"\x10NETWORK_RX_BYTES\x10\x06\x12\x13\n" +
	"\x0fDISK_READ_BYTES\x10\a\x12\x14\n" +
	"\x10DISK_WRITE_BYTES\x10\b\x12\x14\n" +
	"\x10DISK_USAGE_BYTES\x10\t\x12\x14\n" +
	"\x10DISK_TOTAL_BYTES\x10\n" +
	"\"\x88\x01\n" +
	"\x0eIngestResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessageB\x1cZ\x1aprojectz/core/telemetry/v1b\x06proto3"

var (
	file_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_telemetry_v1_telemetry_proto_rawDescData
}

var file_telemetry_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_telemetry_v1_telemetry_proto_goTypes = []any{
	(Metric_Type)(0),       // 0: projectz.telemetry.v1.Metric.Type
	(*TelemetryBatch)(nil), // 1: projectz.telemetry.v1.TelemetryBatch
	(*Metric)(nil),         // 2: projectz.telemetry.v1.Metric
	(*IngestResponse)(nil), // 3: projectz.telemetry.v1.IngestResponse
	nil,                    // 4: projectz.telemetry.v1.Metric.LabelsEntry
}
var file_telemetry_v1_telemetry_proto_depIdxs = []int32{
	2, // 0: projectz.telemetry.v1.TelemetryBatch.metrics:type_name -> projectz.telemetry.v1.Metric
	0, // 1: projectz.telemetry.v1.Metric.type:type_name -> projectz.telemetry.v1.Metric.Type
	4, // 2: projectz.telemetry.v1.Metric.labels:type_name -> projectz.telemetry.v1.Metric.LabelsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_telemetry_v1_telemetry_proto_init() }
func file_telemetry_v1_telemetry_proto_init() {
	if File_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_v1_telemetry_proto_rawDesc), len(file_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_telemetry_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_v1_telemetry_proto = out.File
	file_telemetry_v1_telemetry_proto_goTypes = nil
	file_telemetry_v1_telemetry_proto_depIdxs = nil
}
